# Generated by Django 4.1 on 2025-01-05 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='house',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='user',
            name='police_station',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='street',
            field=models.CharField(max_length=250),
        ),
    ]
