# Generated by Django 4.1 on 2025-01-04 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('img', models.ImageField(upload_to='pics')),
                ('type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('estimated_cost', models.DecimalField(decimal_places=4, max_digits=10)),
                ('status', models.CharField(default='AVAILABLE', max_length=10)),
                ('donation_date', models.DateField()),
                ('donation_time', models.TimeField()),
                ('adoption_date', models.DateField(blank=True, null=True)),
                ('adoption_time', models.TimeField(blank=True, null=True)),
                ('adopter_nid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adopted_pets', to='accounts.adopter', to_field='user_id')),
                ('donor_nid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donated_pets', to='accounts.donor', to_field='user_id')),
            ],
        ),
        migrations.CreateModel(
            name='Vet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('fees', models.DecimalField(decimal_places=4, max_digits=10)),
                ('phone', models.CharField(max_length=15)),
                ('nid', models.BigIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vet_Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('reason', models.TextField()),
                ('medicines', models.CharField(default='No medicines prescribed', max_length=255)),
                ('serial_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='shelterapp.pet', to_field='serial_no')),
                ('vet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vet_visits', to='shelterapp.vet', to_field='nid')),
            ],
        ),
        migrations.CreateModel(
            name='CareTaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_nid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cared_pets', to='accounts.authority', to_field='user_id')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_takers', to='shelterapp.pet', to_field='serial_no')),
            ],
        ),
    ]
