# Generated by Django 4.1 on 2025-01-05 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelterapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='estimated_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='vet',
            name='fees',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
