# Generated by Django 4.1 on 2024-12-26 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelterapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='adoption_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='adoption_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
