# Generated by Django 4.1 on 2024-12-20 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelterapp', '0002_alter_pet_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('ADOPTED', 'Adopted')], default='AVAILABLE', max_length=10),
        ),
    ]
